# Generated by Django 5.0.14 on 2025-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=255, unique=True)),
                ('turkmen', models.CharField(max_length=255)),
            ],
        ),
    ]
