# Generated by Django 5.0.14 on 2025-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='english',
            field=models.CharField(max_length=255),
        ),
    ]
